### PR TITLE
Page migrate

### PR DESCRIPTION
**Pull request by daniel-ortiz**
Hello Jens

This pull request contains the modifications required to integrate my project with autopin+. This only contains the autopin code and the modified perf has to be downloaded separately. I created a branch called PageMigrate.

I will send a detailed description of what I did throughout this weekend...

### CODE REVIEW

**Comment by jbreitbart** [comment]
I didn't look into your code modifications yet, but I like to have the autopin+ repository as self contained as possible. Can you add your lib in a new subdirectory in the vendor directory and include it in the CMake file?

If you have problems adding it to cmake let me know how to build your lib and check how we can integrate it best.

**Comment by daniel-ortiz** [comment]
Hi
I integrated the modified perf into the autopin+ project. It is now under the vendor/perf-pageMigrate. The CMake script was modified as well and it generates the executable with both...

I am not very familiar with pull requests then I basically updated the pageMigrate branch with the requested updates, but I am not sure whether I should create another request or with this is enough.

If anything let me know...

greetings, Daniel

**Comment by jbreitbart** [comment]
Pull requests by default get updated if you commit to the branch you are sending the pull request from, so that is fine. But the travis CI test fails. Can you take a look at that? Maybe there is an additional package required to successfully build it? Just click on details link slightly below this message.

The travis is configure by the .travis file in the root of the repository. I guess taking a look at it is rather self-explanatory if you just need an additional package, but if you have a question just send me an email / ask here.

**Comment by daniel-ortiz** [comment]
Hi

I had not realized about this test, there were several error but it works now...

Daniel

**Comment by jbreitbart** [comment]
I cannot build this version on my system, as it seems to require flex.

config/Makefile:68: *** Error: flex is missing on this system, please install it.  Stop.

Do we really need this? Can we remove this dependency? I'd like to keep the external dependencies as low as possible, as we typically don't have root access for the systems we run autopin on.

**Comment by daniel-ortiz** [comment]
Hi Jens, I pushed a new commit. With this i cover what you wrote on the previous comments:

1. The dependences on Bison and flex have been eliminated.
2. The call to the spm tool has been commented
3. The dead code was removed
4. The signature of the start method changed

**Comment by jbreitbart** [comment]
Thanks. I was able to build it just fine. I haven't tried it yet.

**Comment by daniel-ortiz** [comment]
I just read this. Don't try it. The reason is that soon I will release a new version with a much smaller code size, I will upload the pull request.

**Comment by daniel-ortiz** [comment]
This is replaced by the second version

**Pull request closed without merging**
